version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1

  redis:
    image: 'redis:6-alpine'
    platform: linux/x86_64
    ports:
      - 6389:6379

  backend:
    build: .
    ports:
      - 3000:3000
    environment:
      # app
      - NODE_ENV=development
      - APP_NAME=assignment
      - PORT=3000
      # database
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=1
      - DATABASE_NAME=default
      - DATABASE_LOG_ENABLE=true
      - DATABASE_LIMIT_CONNECTION=5
      # redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
